.\" Man pages for arch-headless

.TH man 1 "2014-11-11" "0.01" "arch-headless man pages"

.SH NAME
.B "arch-headless"
The main purpose of the \fIarch-headless\fR script is to remaster the standard arch linux installation ISO file in order to enable the sshd.service on the standard port, and thus, make it possible for the user to SSH-connect to a headless (and keyboardless) machine running from the remastered-ISO CD/USB.

.SH SYNOPSIS
Run
.RS
.B arch-headless.sh
[\fB\-a\fR\fI 32|64\fR] [\fB-b\fR] [\fB-c\fR] \fIpath/to/file.iso\fR
.RE
.br
where
.RS
\fIpath/to/installation-file.iso\fR is the official installation ISO file as downloaded form \fIhttps://www.archlinux.org/download\fR.
.PP
\fB-a\fR  is the architecture, 32-bit (default) or 64-bit
.PP
\fB-b\fR  halts the script to make manual remstering possible. Re-running the script resumes the script where it was halted to create an ISO file including the manually made modifications.
.PP
\fB-c\fR  drops remastering changes made the first time, and cleans the leftovers.
.RE

.SH "DESCRIPTION"
In order to install arch linux on a headless and keyboardless machine one needs an enabled systemd sshd service. The standard arch linux installation ISO file does not offer that functionality.
.br
The \fIarch-headless\fR script remasters the official installation ISO file in such a way that
.RS
- sshd.service is enabled on port 22 (the standard port)
.br
- ssh paswordless login over SSH is allowed.
.RE
If the remastered ISO is meant to be installed on a USB device, please have a look at the 'SEE ALSO' section below.

.SH OPTIONS
.TP
\fB-a \fIarchitecture\fR
The possible architecture values are \fB32\fR (by default) and \fB64\fR.
.PP
.RS
An assumption was made that this scrit will most likely be used to install arch linux on old computers, so the 32-bit architecture is more likely than not.
.RE
.TP
\fB-b\fR
The script makes all the intended changes within the standard ISO file system and exits before creating the remastered ISO. All the creadted directories are possible to modify, including installing additional software to the remastered ISO. This is not trivial--have a look at the 'SEE ALSO' section below.
.PP
.RS
Run the script again and all the ISO including all the automated and manual modifications will be created, unless the \fB-c\fR option is used.
.RE
.TP
\fB-c\fR
If this option is used, the script will drop all the modifications made in the official ISO file system. All the directories that were created the first time around  will be deleted.

.SH INSTALLATION
As the arch-headless package is in AUR (Arch User Repository) the usual installation methods for AUR packages can be used. And as the arch-headless is just a BASH script, it can be copied to wherever the user needs it.
.br
An automated method is recommended to ensure that all the dependences needed are installed.

.SH CONFIGURATION AND USAGE OF THE SERVICE
No configuration is available; neither it is needed.

.SH SEE ALSO
.TP
.B https://wiki.archlinux.org/index.php/Remastering_the_Install_ISO
Detailed information on how an ISO file can be remastered.
.TP
.B man isohybrid
The isohybrid command belongs to the syslinux package and modifies the ISO file as generated by genisoimage command in such a way that the modified ISO file will work on a USB device.
.br
The author has decided not to include the isohybrid command in this script. But if the remastered ISO is meant to be installed/put on a USB-device (partition), reading the man page for isohybrid is a must.

.SH SPECIAL ISOHYBRID USE EXAMPLE
This example shows how to modify the ISO file so that it can be used on the second partition of a USB flash disk. Note the PARTITON, and not the DEVICE (flash drive).
.PP
.RS
.B isohybrid -e2 -partok remastered-arch.iso
.RE
.PP
The 'partok' tells isohybrid that the ISO file may be put (dd'ed) on a partition rather than the device. The '-e2' means that this will be the second partition.
.PP
You can now dd the remastered-arch.iso to partition 2 of your flash drive.
.PP
.RS
.B dd bs=4M if=/path/to/remastered-arch.iso of=/dev/sdx2 && sync
.RE
.PP
where /dev/sdx is the flash drive.
.br
Do not forget to make partition 2 bootable.


.SH BUGS
Please contact the author if you find any.

.SH AUTHOR
.AU
Wiesław Magusiak <w.magusiak at gmail . com>

.SH COPYRIGHT
Do what you like with the arch-headless, but do not blame the author. No warranty is given, and no responsibility is taken for the use. GPLv3.
